##### for ISCE2 Only #####
#!/usr/bin/env python3

"""
Script to process generated interferogram pairs using mergeBursts.py and apply filtering
This script takes the interferogram pairs generated by ifgram_generation.py
and processes them using the mergeBursts.py script to create merged products,
then applies filtering to the interferograms.
"""

import argparse
import datetime
import glob
import inspect
import os
import sys
import subprocess
import multiprocessing
from concurrent.futures import ProcessPoolExecutor, as_completed

#########################################################################
REFERENCE = """references:

"""

EXAMPLE = """examples:
  python process_ifgrams.py --work-dir /path/to/work --ifgram-dir /path/to/ifgramStack/ifgrams --reference /path/to/reference \
        --isce-home /path/to/isce/home --isce-root /path/to/isce/root \
        --stack-path /path/to/stack --tops-stack-path /path/to/topsStack

  # With filtering and unwrapping
  python process_ifgrams.py --work-dir /path/to/work --ifgram-dir /path/to/ifgramStack/ifgrams --reference /path/to/reference --filter_and_coherence --unwrap --filter-strength 0.5 \
        --isce-home /path/to/isce/home --isce-root /path/to/isce/root \
        --stack-path /path/to/stack --tops-stack-path /path/to/topsStack

  # Parallel processing with filtering and unwrapping
  python process_ifgrams.py --work-dir /path/to/work --ifgram-dir /path/to/ifgramStack/ifgrams --reference /path/to/reference --num-workers 4 --filter_and_coherence --unwrap --filter-strength 0.5 \
        --isce-home /path/to/isce/home --isce-root /path/to/isce/root \
        --stack-path /path/to/stack --tops-stack-path /path/to/topsStack

"""

TEMPLATE = """########## Process Interferogram Pairs
# process generated interferogram pairs using mergeBursts.py and apply filtering and unwrapping
# parameters:
  work_dir = ./              # working directory
  ifgram_dir = ./ifgramStack/ifgrams  # directory containing interferogram pairs
  reference = ./reference    # reference directory
  merge_method = avg         # merge method: top / bot / avg
  multilook = True           # enable multilooking
  azimuth_looks = 3          # number of azimuth looks
  range_looks = 9            # number of range looks
  filter = False             # enable filtering
  filter_strength = 0.5      # filter strength (0.0 to 1.0)
  unwrap = False             # enable unwrapping
  unwrap_method = snaphu     # unwrapping method: snaphu or icu
  defomax = 2.0              # max cycles of deformation for snaphu
  nomcf = False              # run full snaphu (not MCF mode)
  rmfilter = False           # remove filtering effect from final unwrapped interferograms
"""
#########################################################################

def create_parser():
    """
    Create command line argument parser for interferogram processing
    """
    parser = argparse.ArgumentParser(
        description='Process generated interferogram pairs using mergeBursts.py',
        formatter_class=argparse.RawTextHelpFormatter,
        epilog=REFERENCE+'\n'+TEMPLATE+'\n'+EXAMPLE
    )

    # Required parameters
    parser.add_argument('-w','--work-dir', dest='work_dir', default='./',
                       help='Working directory containing all data')
    
    parser.add_argument('--ifgram-dir', dest='ifgram_dir', default='ifgramStack/ifgrams',
                       help='Directory containing generated interferogram pairs')
    
    parser.add_argument('--reference', dest='reference', default='reference',
                       help='Reference directory')

    # Parameters for mergeBursts.py
    merge = parser.add_argument_group('Parameters for mergeBursts.py')
    merge.add_argument('--merge-method', dest='merge_method', default='avg',
                       help='Merge method: top / bot / avg (default: avg)')
    
    merge.add_argument('--merge-aligned', dest='merge_aligned', action='store_true', default=False,
                       help='Use reference information instead of coreg for merged grid')
    
    merge.add_argument('--multilook', dest='multilook', action='store_true', default=True,
                       help='Multilook the merged products (default: True)')
    
    merge.add_argument('--azimuth-looks', dest='azimuth_looks', type=int, default=3,
                       help='Number of azimuth looks (default: 3)')
    
    merge.add_argument('--range-looks', dest='range_looks', type=int, default=9,
                       help='Number of range looks (default: 9)')
    
    merge.add_argument('--name-pattern', dest='name_pattern', default='fine*int',
                       help='Name pattern of burst products to merge (default: fine*int)')
    
    merge.add_argument('--valid-only', dest='valid_only', action='store_true', default=True,
                       help='Only use valid pixels (default: True)')
    
    merge.add_argument('--use-virtual-files', dest='use_virtual_files', action='store_true', default=False,
                       help='Use virtual files instead of actual merging (default: False)')
    
    merge.add_argument('--multilook-tool', dest='multilook_tool', default='isce',
                       help='Tool for multilooking: isce or gdal (default: isce)')
    
    merge.add_argument('--no-data-value', dest='no_data_value', type=float, default=None,
                       help='No data value for GDAL multilooking')


    # Filter parameters
    filter_group = parser.add_argument_group('Filter parameters')
    filter_group.add_argument('--filter_and_coherence', dest='FilterAndCoherence', action='store_true', default=False,
                       help='Apply filtering to interferograms (default: False)')
    
    filter_group.add_argument('-f','--filter-strength', dest='filter_strength', type=float, default=0.5,
                       help='Filter strength (default: 0.5)')
    
    filter_group.add_argument('--filter-type', dest='filter_type', default='goldstein',
                       choices=['goldstein', 'gaussian'],
                       help='Filter type: goldstein or gaussian (default: goldstein)')
    
    filter_group.add_argument('--complex-coherence', dest='complex_coherence', action='store_true', default=False,
                       help='Generate complex coherence from SLCs (default: False)')

    # Unwrapping parameters
    unwrap_group = parser.add_argument_group('Unwrapping parameters')
    unwrap_group.add_argument('--unwrap', dest='unwrap', action='store_true', default=False,
                       help='Enable unwrapping (default: False)')
    
    unwrap_group.add_argument('--unwrap-method', dest='unwrap_method', default='snaphu',
                       choices=['snaphu', 'icu'],
                       help='Unwrapping method: snaphu or icu (default: snaphu)')
    
    unwrap_group.add_argument('--defomax', dest='defomax', type=float, default=2.0,
                       help='Max cycles of deformation for snaphu (default: 2.0)')
    
    unwrap_group.add_argument('--nomcf', dest='nomcf', action='store_true', default=False,
                       help='Run full snaphu and not in MCF mode (default: False)')
    
    unwrap_group.add_argument('--rmfilter', dest='rmfilter', action='store_true', default=False,
                       help='Remove the effect of filtering from final unwrapped interferograms (default: False)')

    # Output parameters
    output = parser.add_argument_group('Output parameters')
    output.add_argument('--output-dir', dest='output_dir', default='ifgramStack/merged_ifgrams',
                       help='Output directory for merged interferograms (default: ifgramStack/merged_ifgrams)')
    
    # output.add_argument('--output-prefix', dest='output_prefix', default='fine',
    #                    help='Prefix for output files (default: merged)')

    # Parallel processing parameters
    parallel = parser.add_argument_group('Parallel processing parameters')
    parallel.add_argument('--num-workers', dest='num_workers', type=int, default=1,
                       help='Number of parallel workers (default: 1 - sequential)')
    
    parallel.add_argument('--continue-on-error', dest='continue_on_error', action='store_true',
                       help='Continue processing other pairs if one fails')
    
    parallel.add_argument('--timeout', dest='timeout', type=int, default=3600,
                       help='Timeout in seconds for each pair processing (default: 3600)')

    # ISCE environment parameters
    isce_env = parser.add_argument_group('ISCE environment parameters')
    isce_env.add_argument('--isce-home', dest='isce_home', required=True,
                       help='Path to ISCE home directory. e.g., /home/xxx/tools/bash/envs/isce2/lib/python3.11/site-packages/isce')
    isce_env.add_argument('--isce-root', dest='isce_root', required=True,
                       help='Path to ISCE root directory. e.g., /home/xxx/tools/bash/envs/isce2/lib/python3.11/site-packages/isce')
    isce_env.add_argument('--stack-path', dest='stack_path', required=True,
                       help='Path to ISCE stack directory. e.g., /home/xxx/tools/isce2/contrib/stack')
    isce_env.add_argument('--tops-stack-path', dest='tops_stack_path', required=True,
                       help='Path to ISCE topsStack directory. e.g., /home/xxx/tools/isce2/contrib/stack/topsStack')

    return parser


def cmd_line_parse(iargs=None):
    """
    Parse command line arguments
    """
    parser = create_parser()
    inps = parser.parse_args(args=iargs)
    return inps


def log(msg):
    """
    Log function to write messages to log file
    """
    f = open('log', 'a')
    callingFunction = os.path.basename(inspect.stack()[1][1])
    dateStr = datetime.datetime.strftime(datetime.datetime.now(), '%Y-%m-%dT%H:%M:%S')
    string = dateStr+" * "+msg
    print(string)
    f.write(string+"\n")
    f.close()


def get_ifgram_pairs(ifgram_dir):
    """
    Get all interferogram pairs from the ifgram directory
    
    Parameters:
    ifgram_dir: Directory containing interferogram pairs
    
    Returns:
    list: List of (date1, date2) tuples
    """
    pairs = []
    
    # Look for directories with pattern YYYYMMDD-YYYYMMDD
    for item in os.listdir(ifgram_dir):
        item_path = os.path.join(ifgram_dir, item)
        if os.path.isdir(item_path) and '_' in item:
            try:
                date1, date2 = item.split('_')
                # Check if both are valid dates (8 digits)
                if len(date1) == 8 and len(date2) == 8 and date1.isdigit() and date2.isdigit():
                    pairs.append((date1, date2, item_path))
            except ValueError:
                continue
    
    print(f"Found {len(pairs)} interferogram pairs in {ifgram_dir}")
    return pairs


def setup_isce_environment(inps):
    """
    Set up ISCE environment variables for subprocess calls
    
    Returns:
    dict: Environment variables dictionary
    """
    env = os.environ.copy()
    
    # Set ISCE paths
    isce_home = inps.isce_home
    isce_root = inps.isce_root
    stack_path = inps.stack_path
    tops_stack_path = inps.tops_stack_path
    
    # Set environment variables
    env['ISCE_HOME'] = isce_home
    env['ISCE_ROOT'] = isce_root
    
    # Update PATH
    env['PATH'] = f"{isce_home}/bin:{isce_home}/applications:{env['PATH']}"
    env['PATH'] = f"{env['PATH']}:{tops_stack_path}"
    
    # Update PYTHONPATH
    pythonpath_parts = [
        isce_root,
        f"{isce_home}/applications",
        f"{isce_home}/components",
        stack_path
    ]
    
    # Add existing PYTHONPATH if it exists
    existing_pythonpath = env.get('PYTHONPATH', '')
    if existing_pythonpath:
        pythonpath_parts.insert(0, existing_pythonpath)
    
    env['PYTHONPATH'] = ':'.join(pythonpath_parts)
    
    return env

def process_single_pair(inps, date1, date2, pair_dir):
    """
    Process a single interferogram pair using mergeBursts.py and apply filtering
    
    Parameters:
    inps: Input parameters object
    date1: Reference date
    date2: Secondary date
    pair_dir: Directory containing the interferogram pair
    
    Returns:
    bool: True if successful, raises exception otherwise
    """
    # Create output directory for this pair
    pair_output_dir = os.path.join(inps.output_dir, f"{date1}_{date2}")
    os.makedirs(pair_output_dir, exist_ok=True)
    
    # Output file name for merged interferogram
    # merged_file = os.path.join(pair_output_dir, f"{inps.output_prefix}_fine.int")
    merged_file = os.path.join(pair_output_dir, "fine.int")
    # Build command line arguments for mergeBursts.py
    merge_cmd_args = [
        'mergeBursts.py',
        '-i', inps.reference,           # Reference directory
        '-d', pair_dir,                 # Directory with products to merge
        '-o', merged_file,              # Output merged file
        '-m', inps.merge_method,        # Merge method
        '--name_pattern', inps.name_pattern,  # Name pattern
    ]
    
    # Add optional parameters to merge command
    if inps.merge_aligned:
        merge_cmd_args.append('-a')
    
    if inps.multilook:
        merge_cmd_args.append('-l')
        merge_cmd_args.extend(['-A', str(inps.azimuth_looks)])
        merge_cmd_args.extend(['-R', str(inps.range_looks)])
    
    if inps.valid_only:
        merge_cmd_args.append('-v')
    
    if inps.use_virtual_files:
        merge_cmd_args.append('-u')
    
    if inps.multilook_tool:
        merge_cmd_args.extend(['-M', inps.multilook_tool])
    
    if inps.no_data_value:
        merge_cmd_args.extend(['-N', str(inps.no_data_value)])
    
    # Set up ISCE environment
    env = setup_isce_environment(inps)
    
    # Build the complete command
    if inps.FilterAndCoherence:
        # Filtered output file
        filtered_file = os.path.join(pair_output_dir, "filt_fine.int")
        coh_file = os.path.join(pair_output_dir,"filt_fine.cor")
        
        # Build filter and coherence command
        filter_cmd_args = [
            'FilterAndCoherence.py',
            '-i', merged_file,              # Input interferogram (merged output)
            '-f', filtered_file,            # Output filtered interferogram
            '-c', coh_file,                 # Coherence file
            '-s', str(inps.filter_strength) # Filter strength
        ]
        
        # Convert command lists to strings
        merge_cmd_str = ' '.join(merge_cmd_args)
        filter_cmd_str = ' '.join(filter_cmd_args)
        
        # Combine commands with && (only run filter if merge succeeds)
        complete_cmd = f"{merge_cmd_str} && {filter_cmd_str}"
        
        print(f"Processing pair: {date1}_{date2}")
        print(f"Input directory: {pair_dir}")
        print(f"Output merged file: {merged_file}")
        print(f"Output filtered file: {filtered_file}")
        print(f"Output coherence file: {coh_file}")
        if inps.unwrap:
            ifg_file = filtered_file
            cor_file = coh_file
            unwrap_file = os.path.join(pair_output_dir, "filt_fine.unw")
            unwrap_cmd_args = [
                'unwrap.py',
                '-i', ifg_file,
                '-c', cor_file,
                '-u', unwrap_file,
                '-m', inps.unwrap_method,
                '-s', inps.reference,
                '--defomax', str(inps.defomax)
            ]
            print(f"Unwrapping enabled with method: {inps.unwrap_method}")
            print(f"Output unwrapped file: {unwrap_file}")
            unwrap_cmd_str = ' '.join(unwrap_cmd_args)
            complete_cmd += f" && {unwrap_cmd_str}"
        
        print(f"Complete command: {complete_cmd}")
    else:
        # Only run merge command
        complete_cmd = ' '.join(merge_cmd_args)
        
        print(f"Processing pair: {date1}_{date2}")
        print(f"Input directory: {pair_dir}")
        print(f"Output merged file: {merged_file}")
        print(f"Command: {complete_cmd}")
    
    # Execute the complete command with custom environment
    try:
        result = subprocess.run(
            complete_cmd, 
            shell=True,  # Use shell=True to allow && operator
            check=True, 
            capture_output=True, 
            text=True,
            timeout=getattr(inps, 'timeout', 3600),
            env=env  # Pass the custom environment
        )
        
        if result.stdout:
            print(f"Output for {date1}_{date2}: {result.stdout.strip()}")
        
        log(f"Successfully processed pair {date1}_{date2}")
        return True
        
    except subprocess.CalledProcessError as e:
        error_msg = f"Command failed with return code {e.returncode}: {e.stderr}"
        print(f"Error processing {date1}_{date2}: {error_msg}")
        log(f"Error processing pair {date1}_{date2}: {error_msg}")
        raise Exception(error_msg)
        
    except subprocess.TimeoutExpired:
        error_msg = f"Processing timed out after {getattr(inps, 'timeout', 3600)} seconds"
        print(f"Error processing {date1}_{date2}: {error_msg}")
        log(f"Error processing pair {date1}_{date2}: {error_msg}")
        raise Exception(error_msg)


def process_single_pair_wrapper(args):
    """
    Wrapper function for parallel processing
    
    Parameters:
    args: Tuple of (inps, date1, date2, pair_dir)
    
    Returns:
    bool: True if successful
    """
    inps, date1, date2, pair_dir = args
    return process_single_pair(inps, date1, date2, pair_dir)


def process_pairs_sequential(inps, pairs):
    """
    Process interferogram pairs sequentially
    
    Parameters:
    inps: Input parameters object
    pairs: List of interferogram pairs with directories
    
    Returns:
    inps: Updated input parameters object
    """
    for date1, date2, pair_dir in pairs:
        process_single_pair(inps, date1, date2, pair_dir)
    
    return inps


def process_pairs_parallel(inps, pairs):
    """
    Process interferogram pairs in parallel using multiple workers
    
    Parameters:
    inps: Input parameters object
    pairs: List of interferogram pairs with directories
    
    Returns:
    inps: Updated input parameters object
    """
    num_workers = min(inps.num_workers, len(pairs), multiprocessing.cpu_count())
    
    print(f"Using {num_workers} parallel workers for {len(pairs)} pairs")
    
    # Use ProcessPoolExecutor for parallel execution
    with ProcessPoolExecutor(max_workers=num_workers) as executor:
        # Submit all tasks
        future_to_pair = {
            executor.submit(process_single_pair_wrapper, (inps, date1, date2, pair_dir)): (date1, date2)
            for date1, date2, pair_dir in pairs
        }
        
        # Collect results as they complete
        successful_pairs = []
        failed_pairs = []
        
        for future in as_completed(future_to_pair):
            pair = future_to_pair[future]
            try:
                result = future.result()
                successful_pairs.append(pair)
                print(f"✓ Successfully completed: {pair[0]}-{pair[1]}")
            except Exception as e:
                failed_pairs.append(pair)
                print(f"✗ Failed: {pair[0]}-{pair[1]} - Error: {str(e)}")
                
                # Stop processing if continue_on_error is False
                if not getattr(inps, 'continue_on_error', False):
                    print("Stopping due to error (continue_on_error=False)")
                    # Shutdown remaining tasks
                    for f in future_to_pair:
                        if not f.done():
                            f.cancel()
                    break
        
        print(f"\nProcessing Summary:")
        print(f"Successful: {len(successful_pairs)} pairs")
        print(f"Failed: {len(failed_pairs)} pairs")
        
        if failed_pairs:
            print("Failed pairs:", failed_pairs)
    
    return inps


def process_ifgram_pairs(inps):
    """
    Main function to process all interferogram pairs
    
    Parameters:
    inps: Input parameters object
    
    Returns:
    inps: Updated input parameters object
    """
    # Get all interferogram pairs
    pairs = get_ifgram_pairs(inps.ifgram_dir)
    
    if not pairs:
        print("No interferogram pairs found!")
        return inps
    
    # Create output directory
    os.makedirs(inps.output_dir, exist_ok=True)
    
    # Process pairs (sequential or parallel)
    if hasattr(inps, 'num_workers') and inps.num_workers > 1:
        print(f"Starting parallel processing with {inps.num_workers} workers")
        inps = process_pairs_parallel(inps, pairs)
    else:
        print("Starting sequential processing")
        inps = process_pairs_sequential(inps, pairs)
    
    # Update inps object
    inps.processed_pairs = pairs
    inps.total_pairs = len(pairs)
    
    return inps


def main(iargs=None):
    """
    Main function to process interferogram pairs
    """
    # Parse command line arguments
    inps = cmd_line_parse(iargs)
    
    # Convert to absolute paths
    inps.work_dir = os.path.abspath(inps.work_dir)
    inps.ifgram_dir = os.path.join(inps.work_dir, inps.ifgram_dir)
    inps.reference = os.path.join(inps.work_dir, inps.reference)
    inps.output_dir = os.path.join(inps.work_dir, inps.output_dir)
    
    # Log start time
    start_time = datetime.datetime.now()
    log(f"Starting interferogram processing at {start_time}")
    log(f"Work directory: {inps.work_dir}")
    log(f"Ifgram directory: {inps.ifgram_dir}")
    log(f"Reference directory: {inps.reference}")
    log(f"Output directory: {inps.output_dir}")
    log(f"Filtering enabled: {inps.FilterAndCoherence}")
    if inps.FilterAndCoherence:
        log(f"Filter type: {inps.filter_type}, Strength: {inps.filter_strength}")
    
    # Process interferogram pairs
    inps = process_ifgram_pairs(inps)
    
    # Log completion
    end_time = datetime.datetime.now()
    duration = end_time - start_time
    log(f"Interferogram processing completed at {end_time}")
    log(f"Total processing time: {duration}")
    
    print("\n" + "="*50)
    print("INTERFEROGRAM PROCESSING COMPLETED SUCCESSFULLY!")
    print(f"Processed {getattr(inps, 'total_pairs', 0)} interferogram pairs")
    print(f"Output directory: {inps.output_dir}")
    if inps.FilterAndCoherence:
        print(f"Filtering applied: {inps.filter_type} with strength {inps.filter_strength}")
    print("="*50)


if __name__ == '__main__':
    main(sys.argv[1:])